seed: 48
batch_size: 512
num_epoch: 60
step_size: 8
gamma: 0.5
weight_decay: 0.0005
lr: 0.0002
lambda_reco_1: 5
lambda_reco_2: 5
lambda_cross_1: 5
lambda_cross_2: 5
lambda_cont_1: 5
lambda_cont_2: 5
lambda_dis: 5
lambda_orthogonal: 0.5
encode_noise_factor: 0.1
decode_noise_factor: 0.1
dataset: sciplex3
mode: cell
encode_batch_norm: true
encode_dropout: 0.2
decode_batch_norm: true
decode_dropout: 0.2
sciplex3_control_train_left: <your_data_path>
sciplex3_control_train_right: <your_data_path>
sciplex3_treat_train_left: <your_data_path>
sciplex3_treat_train_right: <your_data_path>
sciplex3_cross_train_left: <your_data_path>
sciplex3_cross_train_right: <your_data_path>
sciplex3_de_gene: <your_data_path>
sciplex3_mse_de_gene: <your_data_path>
sciplex3_treat_valid_cell_a_with_pert_1_path: <your_data_path>
sciplex3_treat_valid_cell_b_with_pert_1_path: <your_data_path>
sciplex3_control_valid_cell_b_path: <your_data_path>
sciplex3_treat_test_cell_a_with_pert_1_path: <your_data_path>
sciplex3_treat_test_cell_b_with_pert_1_path: <your_data_path>
sciplex3_control_test_cell_b_path: <your_data_path>